services:
  fluent-bit:
    image: fluent/fluent-bit:${FLUENTBIT_VERSION:-latest}
    container_name: fluent-bit
    restart: always
    # network_mode: host
    command: [
      "-c", "/conf/fluent-bit.yml"
    ]
    volumes:
    - ./conf/fluent-bit.yml:/conf/fluent-bit.yml