# mkdir -p grafana_data prometheus_data tempo-data && chown -R 472.472 grafana_data && chown -R 65534:65534 prometheus_data && chown -R 10001:10001 tempo-data
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=dark
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=info
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor tempoServiceGraph
#      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    volumes:
      - ./config/grafana-provisioning-dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      - ./config/grafana-provisioning-datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
      - ./grafana-dashboard/node-exporter-1860.json:/var/lib/grafana/dashboards/node-exporter-1860.json:ro
      - ./grafana-dashboard/kong-7424.json:/var/lib/grafana/dashboards/kong-7424.json:ro
      - ./grafana_data:/var/lib/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    environment:
      - TZ=Asia/Bangkok
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention=30d
      - --web.enable-lifecycle
      - --web.listen-address=0.0.0.0:9090
      - --log.level=debug
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    ports:
      - 9090:9090

  node_exporter:
    image: quay.io/prometheus/node-exporter
    restart: always
    container_name: node-exporter
    environment:
      - TZ=Asia/Bangkok
    # network_mode: host
    pid: host
    # volumes:
    #   - /proc:/host/proc:ro
    #   - /sys:/host/sys:ro
    #   - /:/rootfs:ro
    command:
      - '--web.listen-address=0.0.0.0:9100'

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/loki.yml
    user: root
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./loki-data:/loki
      - ./config/loki.yml:/etc/loki/loki.yml
    ports:
      - 3100:3100
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  fluentbit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluentbit
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    ports:
      - 5170:5170
    volumes:
      - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./config/tempo.yml:/etc/tempo.yml
      - ./tempo-data:/tmp/tempo  # mkdir -p tempo-data && chown -R 10001:10001 tempo-data
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    command: [ "-config.file=/etc/tempo.yml" ]

  pushgateway:
    image: prom/pushgateway:v1.8.0
    container_name: pushgateway
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - 9091:9091
