auth_enabled: false

server:
  http_listen_port: 3100
#  grpc_listen_port: 9095

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist #inmemory
  replication_factor: 1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

memberlist:
  join_members:
  - loki:7946

schema_config:
  configs:
    - from: 2024-06-04
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h  #168h

#storage_config:
#  filesystem:
#    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 720h  # 30 day
  max_query_series: 1000000
  max_query_parallelism: 2

#chunk_store_config:
#  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  compaction_interval: 5m
  shared_store: filesystem

#ruler:
#  alertmanager_url: http://localhost:9093
