global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  
  - job_name: prometheus
    static_configs:
      - targets:
        - 127.0.0.1:9090

  - job_name: tempo
    static_configs:
      - targets: [ "tempo:3200"]
  
  - job_name: kong
    static_configs:
      - targets:
        - kong:8001
  
  - job_name: node-exporter
    static_configs:
      - targets:
        - node-exporter:9100
  
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets:
        - pushgateway:9091
